### ISSUE TITLE
Change Search Icon into a font icon rather than an image icon

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#12]
The theme setting that adds a search icon to the navigation uses an image for the icon. This makes it hard to help users adjust the color. It would be a good idea to convert this into a font icon so that if the user adjusts the color of the menu item links, the search icon will be adjusted too.

**Comment by AlexGStapleton** [comment]
Wait, was this setting removed? I can see it in the code, but can't seem to see it in the latest development build.

**Comment by Misplon** [comment]
There isn't a header search option in Focus at the moment. Not sure if there ever was at a public/visible code level.

**Comment by Misplon** [comment]
Perhaps change this issue title and we'll make it a task to add that setting. Thanks.

**Comment by AlexGStapleton** [comment]
[Here's the default setting value](https://github.com/siteorigin/focus/blame/develop/inc/settings.php#L178)

[He's the search header functionality](https://github.com/siteorigin/focus/blame/develop/inc/plus.php#L79)

**Comment by AlexGStapleton** [comment]
Added a new issue for adding this setting #17 as this is a separate issue.
