### ISSUE TITLE
Single Post Navigation: Add next and previous inline with video

### ISSUE THREAD

**Issue by Misplon** [siteorigin/focus#16]
Add single post navigation arrows to the right and left of the video. Might need to make this a default off setting.

<img width="1435" alt="single-focus" src="https://cloud.githubusercontent.com/assets/789159/17322174/7400540a-589c-11e6-9735-ed8c0c79db5e.png">

**Comment by gregpriday** [comment]
Yeah, I like this idea.

**Comment by adiraomj** [comment]
Nice idea. Where do you think we should place the arrows on smaller screens?

**Comment by Misplon** [comment]
Any references from other services like YouTube or Vimeo? 

Would it work to place them below the video on mobile?

**Comment by adiraomj** [comment]
Yeah. Placing it below the video would be neat way to go. I'll send a PR with that, after which we could fine tune it if need be. :)
