### ISSUE TITLE
Output Featured Images on Pages

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#22]
Currently you're able to set a featured image on a page, but they won't output.

**Comment by adiraomj** [comment]
The featured image is used as a background for `#single-header`. It is the same as how it id output in posts.

Ref : https://github.com/siteorigin/focus/blob/develop/page.php#L15-L18

**Comment by AlexGStapleton** [comment]
Huh, that's odd. I can't seem to see it. :confused:

**Comment by Misplon** [comment]
<img width="1414" alt="featured" src="https://cloud.githubusercontent.com/assets/789159/17631598/07c1b4a6-60c5-11e6-9073-47b2f965a2b2.png">

**Comment by AlexGStapleton** [comment]
Oh I'm blind.
