### ISSUE TITLE
Add a new page template to recreate the home page layout

### ISSUE THREAD

**Issue by Misplon** [siteorigin/focus#28]
With our loop templates ready we just need a page template so that users can re-create the home page layout. Home Page Template seems a bit limited as this can be used for building archive pages in PB. Should we perhaps call it: `Full-Width - No Title`

**Comment by adiraomj** [comment]
Great idea @Misplon. 

So just to clarify, the `Full-Width - No Title` template is the `Full Width` template minus the[`#single-header`](https://github.com/siteorigin/focus/blob/develop/page-full.php#L17-L35) section.

**Comment by Misplon** [comment]
@adiraomj Apologies for missing this. Yes, that's correct. `Full-Width - No Title` is the current `Full-Width` template minus `#single-header`.
