### ISSUE TITLE
Videos: Add ability to use Focus Video Plugin on pages

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#3]
The ability to embed videos (via the Focus Video functionality) on pages has been requested quite often in my experience. It adds a more consistent look to the website as normally you would have to embed inside of the post rather than the typical above the post location.

**Comment by Misplon** [comment]
@adiraomj Thanks dude. The functionality is now ready in Focus Videos we just need to add the output in pages in the theme and supporting styles.
