### ISSUE TITLE
When Use First Page Builder Row enabled, video hidden

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#39]
When you enable the "Use First Page Builder Row", it prevents the video plugin from outputting the video itself. There are a number of instances where this could be undesired so it might be a good idea to fix it.

**Comment by Misplon** [comment]
@AlexGStapleton, hey :) The `Use First Page Builder Row` setting requires the `Full Width - No Title` page template. That template removes the `#single-header` in order to display as intended. So for now, we're going to call this a limitation of the settings combinations.

**Comment by AlexGStapleton** [comment]
Ah, makes sense. Thanks for letting me know mate. :)
