### ISSUE TITLE
Incorrect reference to jPlayer

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#51]
[The enqueue](https://github.com/siteorigin/focus/blob/develop/inc/video.php#L142) for the jPlayer js actually points to the wrong location of /jplayer/jquery.jplayer.(min).js rather than [js/jplayer/jquery.jplayer.(min).js](https://github.com/siteorigin/focus/blob/develop/js/jplayer/jquery.jplayer.min.js).

[Example URL](https://demo.siteorigin.com/focus/2013/02/20/the-mountain/)

**Comment by AlexGStapleton** [comment]
Oh, and it looks like jplayer is, by default, minified. It's also named as such, [jquery.jplayer.min.js](https://github.com/siteorigin/focus/blob/develop/js/jplayer/jquery.jplayer.min.js)

Maybe we should add either the normal version or exclude this file from the build script (to prevent double minification)?

**Comment by Misplon** [comment]
Sorry for missing this. Nice catch. We're required to include the un-minified version. Will aim for an update tomorrow if possible. Going to add a few menu color settings. Let me know if you need anything else in there.
