### ISSUE TITLE
Focus: Thumbnail Pagination doesn't seem to work for certain users

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#59]
The thumbnail grid pagination doesn't seem to be working for some users. Basically, a few things can happen:

paged gets reset (page gets removed from the URL) < I was able to replicate this
Newer Posts never shows up

[Reference Layout](https://u.teknik.io/mMyvj.json)
[Exported Customizer data](https://u.teknik.io/a5wLb.dat). ([Customizer Export/Import](https://wordpress.org/plugins/customizer-export-import/))

**Comment by AlexGStapleton** [comment]
@Misplon Were you able to replicate this with the provided files?

**Comment by Misplon** [comment]
I'm getting this error when trying to import Customizer settings:

`Error importing settings! The settings you uploaded are not for the current theme.`

I've tried with both Focus and Focus Child. Mmm, what am I missing?

**Comment by AlexGStapleton** [comment]
OH. Sorry, I forgot that I had renamed it the theme directory.

Try: https://u.teknik.io/a5wLb.dat

**Comment by Misplon** [comment]
Thanks. The error I'm getting now is:

`Error importing settings! Please check that you uploaded a customizer export file.`

**Comment by AlexGStapleton** [comment]
Wel,l that's odd - it works without issue for me. Hm, I wonder... try this version: https://u.teknik.io/7uYu2.dat

**Comment by Misplon** [comment]
Thanks dude.

Phew, even with the JSON layout loaded up and Customizer settings imported, I still can't replicate.

**Comment by AlexGStapleton** [comment]
Well crap. Hm. To clarify, what steps are you taking to replicate this issue?

You should be able to replicate this issue by adding a post loop widget with the thumbnail grid selected, and then click the next / previous posts link (can't remember which one it is off the top of my head). It's never transition onto the next page.

**Comment by adiraomj** [comment]
I was unable to replicate as well.. I used the Customizer Import/export plugin. Imported the file you provided. Imported the layout file you provided in a new page. Unable to find any issue.

**Comment by Misplon** [comment]
@AlexGStapleton Correct, those are the same steps I'm taking. 

Ok so let's troubleshoot what might be causing this on your install. Plugins?

**Comment by AlexGStapleton** [comment]
Latest version of Focus with only Page Builder, Widgets Bundle, and SiteOrigin CSS active. :S

**Comment by Misplon** [comment]
@AlexGStapleton Not sure what you want to do here. Can you see the cause of the problem in your install?

**Comment by Misplon** [comment]
Is this still going down?

**Comment by AlexGStapleton** [comment]
Yes, I'm still able to replicate this issue.

**Comment by Misplon** [comment]
Thanks. Are you able to see the cause of the issue? Previously, both Adi and I struggled to replicate.

**Comment by AlexGStapleton** [comment]
Hm. I was using the loop on a post rather than a page and it appears to work without issue on a page. Did you try the post loop in a post?
