### ISSUE TITLE
Add a widget area to the recent posts page

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#6]
The big highlight of the focus theme is honestly the recent posts page which is great however it offers next to zero customization options. I think a widget area or two would really help improve this page. The widget area could go before the "videos" or / and after the videos.

**Comment by adiraomj** [comment]
@Misplon should I add widget areas only for the recent posts page or across all archive pages?
Secondly, I think we can add 2 widget areas ( above and below posts ). What do you think?

**Comment by AlexGStapleton** [comment]
@adiraomj With #10 in the works I'm not too sure if this issue is required anymore. @Misplon thoughts?

**Comment by Misplon** [comment]
Yes, I think given #10 which will give users the ability to reconstruct the home page we can close this issue. If requests come up specifically for new widget areas we can re-look at this. Thanks guys.
