### ISSUE TITLE
Update Theme Settings Framework

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/focus#64]
A user reported receiving an error message in the customizer after installing Focus. I went to see why this issue was occurring and found that this issue has already been fixed [here](https://github.com/siteorigin/settings/commit/3d18ac5b3d92c0bae3cad43505176691a5450512). To resolve this issue, we'll need to release a theme update with the updated Theme Settings Framework.

![](https://i.imgur.com/nbZ5jXi.png)

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/focus/commit/4328f2245bc20baef77c86345f2575435fe0581d.
